import { FlamObject } from '@/types/canvas';
import { v4 as uuidv4 } from 'uuid';

// ─── AURA HEADPHONES Demo Scene ───────────────────────────────────────────────
// A fictional product campaign that demonstrates FLAMBOARD's core value:
// Draw → Collaborate → Make Interactive → Experience

export function createDemoScene(): FlamObject[] {
  return [
    // Background card / product stage
    {
      id: uuidv4(),
      type: 'rect',
      name: 'Background Stage',
      position: { x: 80, y: 60 },
      size: { width: 720, height: 480 },
      rotation: 0,
      depth: 0,
      opacity: 1,
      locked: false,
      visible: true,
      fill: '#F5EDE3',
      stroke: '#E8D5C0',
      strokeWidth: 1,
      cornerRadius: 16,
      intent: 'decorative',
    },

    // Ambient warm circle behind product
    {
      id: uuidv4(),
      type: 'ellipse',
      name: 'Ambient Glow',
      position: { x: 300, y: 160 },
      size: { width: 260, height: 260 },
      rotation: 0,
      depth: 1,
      opacity: 0.35,
      locked: false,
      visible: true,
      fill: '#E8A87C',
      stroke: undefined,
      strokeWidth: 0,
      intent: 'decorative',
    },

    // Headphone product shape (simplified ellipse + arc representation)
    {
      id: uuidv4(),
      type: 'ellipse',
      name: 'Headphone Left Cup',
      position: { x: 335, y: 220 },
      size: { width: 75, height: 95 },
      rotation: -8,
      depth: 2,
      opacity: 1,
      locked: false,
      visible: true,
      fill: '#2C1810',
      stroke: '#4A3020',
      strokeWidth: 2,
      intent: 'product',
      interaction: {
        type: 'rotate',
        rotationSpeed: 1.5,
      },
    },

    {
      id: uuidv4(),
      type: 'ellipse',
      name: 'Headphone Right Cup',
      position: { x: 465, y: 225 },
      size: { width: 75, height: 95 },
      rotation: 8,
      depth: 2,
      opacity: 1,
      locked: false,
      visible: true,
      fill: '#2C1810',
      stroke: '#4A3020',
      strokeWidth: 2,
      intent: 'product',
      interaction: {
        type: 'rotate',
        rotationSpeed: 1.5,
      },
    },

    // Headband arc (rect approximation)
    {
      id: uuidv4(),
      type: 'rect',
      name: 'Headphone Band',
      position: { x: 355, y: 185 },
      size: { width: 165, height: 55 },
      rotation: 0,
      depth: 2,
      opacity: 1,
      locked: false,
      visible: true,
      fill: '#1A0F08',
      stroke: '#3A2010',
      strokeWidth: 2,
      cornerRadius: 35,
      intent: 'product',
    },

    // Inner ear pad highlight
    {
      id: uuidv4(),
      type: 'ellipse',
      name: 'Left Ear Pad',
      position: { x: 348, y: 235 },
      size: { width: 50, height: 65 },
      rotation: -8,
      depth: 3,
      opacity: 1,
      locked: false,
      visible: true,
      fill: '#3D2415',
      stroke: undefined,
      strokeWidth: 0,
      intent: 'decorative',
    },

    {
      id: uuidv4(),
      type: 'ellipse',
      name: 'Right Ear Pad',
      position: { x: 476, y: 240 },
      size: { width: 50, height: 65 },
      rotation: 8,
      depth: 3,
      opacity: 1,
      locked: false,
      visible: true,
      fill: '#3D2415',
      stroke: undefined,
      strokeWidth: 0,
      intent: 'decorative',
    },

    // Product name
    {
      id: uuidv4(),
      type: 'text',
      name: 'Product Name',
      position: { x: 155, y: 385 },
      size: { width: 300, height: 60 },
      rotation: 0,
      depth: 4,
      opacity: 1,
      locked: false,
      visible: true,
      text: 'AURA',
      fontSize: 54,
      fontFamily: 'Lora, Georgia, serif',
      fontStyle: 'bold',
      fill: '#1A0F08',
      align: 'left',
      intent: 'information',
    },

    // Tagline
    {
      id: uuidv4(),
      type: 'text',
      name: 'Tagline',
      position: { x: 155, y: 445 },
      size: { width: 320, height: 30 },
      rotation: 0,
      depth: 4,
      opacity: 1,
      locked: false,
      visible: true,
      text: 'Premium Sound. Wireless Freedom.',
      fontSize: 14,
      fontFamily: 'Inter, sans-serif',
      fill: '#6B4C35',
      align: 'left',
      intent: 'information',
    },

    // Spec badges
    {
      id: uuidv4(),
      type: 'rect',
      name: 'Spec Badge 1',
      position: { x: 155, y: 490 },
      size: { width: 110, height: 34 },
      rotation: 0,
      depth: 4,
      opacity: 1,
      locked: false,
      visible: true,
      fill: '#2C1810',
      cornerRadius: 17,
      intent: 'information',
    },

    {
      id: uuidv4(),
      type: 'text',
      name: 'Spec Text 1',
      position: { x: 155, y: 499 },
      size: { width: 110, height: 20 },
      rotation: 0,
      depth: 5,
      opacity: 1,
      locked: false,
      visible: true,
      text: '40hr Battery',
      fontSize: 12,
      fontFamily: 'Inter, sans-serif',
      fill: '#F5EDE3',
      align: 'center',
      intent: 'information',
    },

    {
      id: uuidv4(),
      type: 'rect',
      name: 'Spec Badge 2',
      position: { x: 278, y: 490 },
      size: { width: 110, height: 34 },
      rotation: 0,
      depth: 4,
      opacity: 1,
      locked: false,
      visible: true,
      fill: '#2C1810',
      cornerRadius: 17,
      intent: 'information',
    },

    {
      id: uuidv4(),
      type: 'text',
      name: 'Spec Text 2',
      position: { x: 278, y: 499 },
      size: { width: 110, height: 20 },
      rotation: 0,
      depth: 5,
      opacity: 1,
      locked: false,
      visible: true,
      text: 'ANC Pro',
      fontSize: 12,
      fontFamily: 'Inter, sans-serif',
      fill: '#F5EDE3',
      align: 'center',
      intent: 'information',
    },

    // CTA Button
    {
      id: uuidv4(),
      type: 'rect',
      name: 'CTA Button',
      position: { x: 530, y: 450 },
      size: { width: 170, height: 50 },
      rotation: 0,
      depth: 4,
      opacity: 1,
      locked: false,
      visible: true,
      fill: '#C77B5A',
      cornerRadius: 25,
      intent: 'cta',
      interaction: {
        type: 'openLink',
        url: '#',
      },
    },

    {
      id: uuidv4(),
      type: 'text',
      name: 'CTA Text',
      position: { x: 530, y: 462 },
      size: { width: 170, height: 30 },
      rotation: 0,
      depth: 5,
      opacity: 1,
      locked: false,
      visible: true,
      text: 'Explore →',
      fontSize: 16,
      fontFamily: 'Inter, sans-serif',
      fontStyle: 'bold',
      fill: '#FFFFFF',
      align: 'center',
      intent: 'cta',
    },

    // Hotspot marker
    {
      id: uuidv4(),
      type: 'hotspot',
      name: 'Info Hotspot',
      position: { x: 600, y: 210 },
      size: { width: 36, height: 36 },
      rotation: 0,
      depth: 6,
      opacity: 1,
      locked: false,
      visible: true,
      fill: '#C77B5A',
      text: 'i',
      fontSize: 16,
      fontFamily: 'Inter, sans-serif',
      intent: 'hotspot',
      interaction: {
        type: 'reveal',
        revealContent: 'Crafted with premium 40mm drivers for studio-quality sound. Foldable design for travel.',
      },
    },

    // Handwritten annotation 1
    {
      id: uuidv4(),
      type: 'text',
      name: 'Annotation 1',
      position: { x: 640, y: 155 },
      size: { width: 160, height: 50 },
      rotation: -3,
      depth: 7,
      opacity: 0.75,
      locked: false,
      visible: true,
      text: '← Make this interactive',
      fontSize: 13,
      fontFamily: 'Caveat, cursive',
      fill: '#9B6B4A',
      align: 'left',
      intent: 'decorative',
      demoAnnotation: 'true',
    },

    // Handwritten annotation 2
    {
      id: uuidv4(),
      type: 'text',
      name: 'Annotation 2',
      position: { x: 90, y: 390 },
      size: { width: 140, height: 40 },
      rotation: 2,
      depth: 7,
      opacity: 0.65,
      locked: false,
      visible: true,
      text: 'maybe serif here?',
      fontSize: 12,
      fontFamily: 'Caveat, cursive',
      fill: '#9B6B4A',
      align: 'left',
      intent: 'decorative',
      demoAnnotation: 'true',
    },

    // Annotation 3
    {
      id: uuidv4(),
      type: 'text',
      name: 'Annotation 3',
      position: { x: 490, y: 395 },
      size: { width: 130, height: 40 },
      rotation: -2,
      depth: 7,
      opacity: 0.65,
      locked: false,
      visible: true,
      text: 'CTA could be bolder',
      fontSize: 12,
      fontFamily: 'Caveat, cursive',
      fill: '#9B6B4A',
      align: 'left',
      intent: 'decorative',
      demoAnnotation: 'true',
    },
  ];
}
